# Minimal Docker Compose override for Raspberry Pi
# This file disables resource-intensive services not required for basic GeoSight operation
version: '3.9'

services:
  # Disable webpack to save resources on Raspberry Pi
  # Frontend assets will be served from pre-built static files
  webpack:
    deploy:
      replicas: 0
    # Alternative: comment out the entire service by prefixing with x-
  
  # Make dev service not depend on webpack
  dev:
    depends_on:
      - db
      - redis
      - worker
    # Remove webpack dependency
